export { default as logoImg } from 'assets/images/logo.png'
export { default as sudokuTest1 } from 'assets/images/sudoku-test-1.jpg'
export { default as sudokuTest2 } from 'assets/images/sudoku-test-2.webp'
export { default as sudokuTest3 } from 'assets/images/sudoku-test-3.png'
export { default as sudokuTest4 } from 'assets/images/sudoku-test-4.png'
export { default as sudokuTest5 } from 'assets/images/sudoku-test-5.jpeg'
