version: '3.8'

services:
  ai-backend:
    container_name: sudoku-solver-ai-backend
    build:
      context: backends/ai-backend
      dockerfile: Dockerfile
    hostname: ai-backend
    ports:
      - ${AI_API_PORT}:${AI_API_PORT}
    networks:
      - local_net
    environment:
      - DEVELOP_MODE=${AI_API_DEVELOP_MODE}
      - APP_PORT=${AI_API_PORT}
      - API_HOST=${AI_API_HOST}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_END_POINT=${AWS_END_POINT}
    volumes:
      - ./backends/ai-backend:/ai-backend
    command: uvicorn app:app --host 0.0.0.0 --port ${AI_API_PORT} --reload

  db-backend:
    container_name: sudoku-solver-db-backend
    build:
      context: backends/db-backend
      dockerfile: Dockerfile
    hostname: db-backend
    volumes:
      - ./backends/db-backend:/db-backend
    ports:
      - ${DB_API_PORT}:${DB_API_PORT}
    environment:
      - AI_BACKEND_URL=http://ai-backend:${AI_API_PORT}
      - APP_PORT=${DB_API_PORT}
      - DB_PASS=${DB_PASS}
      - DB_USERNAME=${DB_USERNAME}
      - DB_CONNECTION_LINK=${DB_CONNECTION_LINK}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_END_POINT=${AWS_END_POINT}
    depends_on:
      - ai-backend

  client:
    container_name: sudoku-solver-web-client
    build:
      context: client
      dockerfile: Dockerfile
      target: development
    hostname: web-client
    volumes:
      - ./client:/client
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    depends_on:
      - ai-backend
      - db-backend
    environment:
      - VITE_APP_MAIN_BACKEND_URL=http://db-backend:${DB_API_PORT}
    networks:
      - local_net

networks:
  local_net:
    driver: bridge
